library(kernlab)
data(cars)
plot(cars$speed,cars$dist)
model<- rvm(cars$speed,cars$dist)
ytest<- predict(model,cars$speed)
lines(cars$speed,ytest,col="red")
models2<-rvm(cars$speed,cars$dist,cross=6,fit=T,interactions=1,tol=0.01)
ytest <- predict(models2,cars$speed)  
lines(cars$speed,ytest,col="yellow")