# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/precise64"
    node1.vm.hostname = 'node1'
    node1.vm.box_url = "ubuntu/precise64"
    node1.vm.provision "shell", path: "provision.sh"
    #node1.vm.network :private_network, ip: "192.168.50.1"    
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/precise64"
    node2.vm.hostname = 'node2'
    node2.vm.box_url = "ubuntu/precise64"
    node2.vm.provision "shell", path: "provision.sh"
    #node2.vm.network :private_network, ip: "192.168.50.2"
  end

end