package com.github.diegopacheco.sandbox.scalaz.code.for0.terrans.lists

import scalaz._
import Scalaz._
import scalaz.BKTree

//
// BKTree: A Burkhard-Keller tree for fast approximation-based searches -- ever wondered why Google knows what you really meant, 
// so quickly? Here is a great explanation of a B-K Tree | BKTree | Example
//
object ScalaZBKTreeApp extends App {
	 
    val dictionary = List("S","S's","Saab","Saab's","Saar","Saar's","Saarinen","Saarinen's","Sabbath","Sabbath's","Sabbaths",
    					  "Sabik","Sabik's","Sabin","Sabin's","Sabina","Sabina's","Sabine","Sabine's","Sabre","Sabre's",
    					  "Sabrina","Sabrina's","Sacajawea","Sacco","Sacco's","Sachs","Sachs's","Sacramento","Sacramento's",
    					  "Sadat","Sadat's","Saddam","Saddam's","Sadducee","Sadducee's","Sade","Sade's","Sadie","Sadie's",
    					  "Sadr","Sadr's","Safavid","Safavid's","Safeway","Safeway's","Sagan","Sagan's","Saginaw","Saginaw's",
    					  "Sagittarius","Sagittarius's","Sagittariuses","Sahara","Sahara's","Sahel","Saigon","Saigon's","Saiph",
    					  "Saiph's","Sakai","Sakai's","Sakha","Sakha's","Sakhalin","Sakhalin's","Sakharov","Sakharov's","Saki",
    					  "Saki's","Saks","Sal","Sal's","Saladin","Saladin's","Salado","Salado's","Salamis","Salamis's","Salas",
    					  "Salas's","Salazar","Salazar's","Salem","Salem's","Salerno","Salerno's","Salinas","Salinger","Salinger's",
    					  "Salisbury","Salisbury's","Salish","Salish's","Salk","Salk's","Sallie","Sallie's","Sallust","Sallust's",
    					  "Sally","Sally's","Salome","Salome's","Salton","Salton's","Salvador","Salvador's","Salvadoran","Salvadorans",
    					  "Salvadorian","Salvadorians","Salvatore","Salvatore's","Salween","Salween's","Salyut","Salyut's",
    					  "Sam","Sam's","Samantha","Samantha's","Samar","Samar's","Samara","Samara's","Samaritan","Samaritan's",
    					  "Samaritans","Samarkand","Samarkand's","Sammie","Sammie's","Sammy","Sammy's","Samoa","Samoan","Samoset",
    					  "Samoset's","Samoyed","Samoyed's","Sampson","Sampson's","Samson","Samson's","Samsonite","Samsonite's",
    					  "Samuel","Samuel's","Samuelson","Samuelson's","San","San's","Sana","Sana's","Sanchez","Sanchez's","Sancho",
    					  "Sancho's","Sand","Sand's","Sandburg","Sandburg's","Sanders","Sandinista","Sandoval","Sandoval's","Sandra",
    					  "Sandra's","Sandy","Sandy's","Sanford","Sanford's","Sanforized","Sang","Sang's","Sanger","Sanger's","Sanhedrin",
    					  "Sanhedrin's","Sanka","Sanka's","Sankara","Sankara's","Sanskrit","Sanskrit's","Santa","Santa's","Santana",
    					  "Santana's","Santayana","Santayana's","Santeria","Santiago","Santiago's","Santos","Sappho","Sappho's",
    					  "Sapporo","Sapporo's","Sara","Sara's","Saracen","Saracen's","Saracens","Saragossa","Saragossa's","Sarah",
    					  "Sarah's","Sarajevo","Sarajevo's","Saran","Saran's","Sarasota","Sarasota's","Saratov","Saratov's","Sarawak",
    					  "Sarawak's","Sardinia","Sardinia's","Sargasso","Sargasso's","Sargent","Sargent's","Sargon","Sargon's",
    					  "Sarnoff","Sarnoff's","Saroyan","Saroyan's","Sarto","Sarto's","Sartre","Sartre's","Sasha","Sasha's",
    					  "Saskatchewan","Saskatchewan's","Saskatoon","Saskatoon's","Sasquatch","Sassanian","Sassoon","Sassoon's",
    					  "Sat","Sat's","Satan","Satan's","Satanism","Satanism's","Satanist","Satanist's","Saturday","Saturday's",
    					  "Saturdays","Saturn","Saturn's","Saturnalia","Saturnalia's","Saudi","Saudis","Saul","Saul's","Saunders",
    					  "Saundra","Saundra's","Saussure","Saussure's","Sauterne","Savage","Savage's","Savannah","Savannah's","Savior",
    					  "Savior's","Savonarola","Savonarola's","Savoy","Savoy's","Savoyard","Savoyard's","Sawyer","Sawyer's",
    					  "Saxon","Saxon's","Saxons","Saxony","Saxony's","Sayers","Sb","Sb's","Sc","Sc's","Scandinavia",
    					  "Scandinavia's","Scandinavian","Scandinavians","Scaramouch","Scaramouch's","Scarborough","Scarborough's",
    					  "Scarlatti","Scarlatti's","Scheat","Scheat's","Schedar","Schedar's","Scheherazade","Scheherazade's","Schelling",
    					  "Schelling's","Schenectady","Schenectady's","Schick","Schick's","Schiller","Schiller's","Schindler",
    					  "Schindler's","Schlesinger","Schlesinger's","Schliemann","Schliemann's","Schlitz","Schlitz's","Schmidt",
    					  "Schmidt's","Schnabel","Schnabel's","Schnauzer","Schnauzer's","Schneider","Schneider's","Schoenberg",
    					  "Schoenberg's","Schopenhauer","Schopenhauer's","Schrieffer","Schrieffer's","Schroeder","Schroeder's",
    					  "Schrödinger","Schubert","Schubert's","Schultz","Schultz's","Schulz","Schulz's","Schumann","Schumann's",
    					  "Schuyler","Schuyler's","Schuylkill","Schuylkill's","Schwartz","Schwartz's","Schwarzenegger",
    					  "Schwarzenegger's","Schwarzkopf","Schwarzkopf's","Schweitzer","Schweitzer's","Schweppes",
    					  "Schweppes's","Schwinger","Schwinger's","Schwinn","Schwinn's","Scientology","Scientology's","Scipio",
    					  "Scipio's","Scopes","Scopes's","Scorpio","Scorpio's","Scorpios","Scorpius","Scorpius's","Scorsese",
    					  "Scorsese's","Scot","Scot's","Scotch","Scotches","Scotchman","Scotchman's","Scotchmen","Scotland",
    					  "Scotland's","Scots","Scotsman","Scotsman's","Scotsmen","Scotswoman","Scotswomen","Scott",
    					  "Scott's","Scottie","Scottie's","Scottish","Scottsdale","Scottsdale's","Scotty","Scotty's",
    					  "Scrabble","Scrabble's","Scranton","Scranton's","Scriabin","Scriabin's","Scribner","Scribner's",
    					  "Scripture","Scripture's","Scriptures","Scrooge","Scrooge's","Scruggs","Scruggs's","Scud","Sculley",
    					  "Sculley's","Scylla","Scylla's","Scythia","Scythia's","Scythian","Se","Seaborg","Seaborg's","Seagram",
    					  "Seagram's","Sean","Sean's","Sears","Sears's","Seattle","Seattle's","Sebastian","Sebastian's","Sec",
    					  "Seconal","Secretariat","Secretariat's","Secretaries","Secretary","Seder","Seder's","Seders",
    					  "Seebeck","Seebeck's","Sega","Sega's","Segovia","Segovia's","Segre","Segre's","Segundo","Segundo's",
    					  "Seiko","Seiko's","Seine","Seine's","Seinfeld","Seinfeld's","Sejong","Sejong's","Selassie","Selassie's",
    					  "Selectric","Selectric's","Selena","Selena's","Seleucid","Seleucid's","Seleucus","Seleucus's","Selim",
    					  "Selim's","Seljuk","Seljuk's","Selkirk","Selkirk's","Sellers","Sellers's","Selma","Selma's","Selznick",
    					  "Selznick's","Semarang","Semarang's","Seminole","Seminole's","Seminoles","Semiramis","Semiramis's","Semite",
    					  "Semite's","Semites","Semitic","Semitic's","Semitics","Semtex","Sen","Senate","Senate's","Senates","Senator",
    					  "Sendai","Sendai's","Seneca","Seneca's","Senecas","Senegal","Senegal's","Senegalese","Senghor","Senghor's",
    					  "Senior","Seniors","Sennacherib","Sennacherib's","Sennett","Sennett's","Sensurround","Sensurround's","Seoul",
    					  "Seoul's","Sephardi","Sephardi's","Sepoy","Sepoy's","Sept","Sept's","September","September's","Septembers",
    					  "Septuagint","Septuagint's","Septuagints","Sequoya","Sequoya's","Serb","Serb's","Serbia","Serbia's","Serbian",
    					  "Serbians","Serbs","Serena","Serena's","Serengeti","Serengeti's","Sergei","Sergei's","Sergio","Sergio's",
    					  "Serpens","Serpens's","Serra","Serra's","Serrano","Serrano's","Set","Set's","Seth","Seth's","Seton","Seton's",
    					  "Seurat","Seurat's","Seuss","Seuss's","Sevastopol","Sevastopol's","Severn","Severn's","Severus","Severus's",
    					  "Seville","Seville's","Seward","Seward's","Sextans","Sextans's","Sexton","Sexton's","Seychelles","Seyfert",
    					  "Seymour","Seymour's","Sgt","Shackleton","Shackleton's","Shaffer","Shaffer's","Shaka","Shaka's","Shakespeare",
    					  "Shakespeare's","Shakespearean","Shakespeareans","Shana","Shana's","Shane","Shane's","Shanghai",
    					  "Shanghai's","Shanna","Shanna's","Shannon","Shannon's","Shantung","Shantung's","Shapiro","Shapiro's",
    					  "Shari","Shari'a","Shari's","Sharlene","Sharlene's","Sharon","Sharon's","Sharp","Sharp's","Sharpe",
    					  "Sharpe's","Sharron","Sharron's","Shasta","Shasta's","Shaula","Shaula's","Shaun","Shaun's","Shauna",
    					  "Shauna's","Shavian","Shavuot","Shavuot's","Shaw","Shaw's","Shawn","Shawn's","Shawna","Shawna's",
    					  "Shawnee","Shawnee's","Shcharansky","Shcharansky's","Shea","Shea's","Sheba","Sheba's","Shebeli",
    					  "Shebeli's","Sheena","Sheena's","Sheetrock","Sheffield","Sheffield's","Sheila","Sheila's","Shelby",
    					  "Shelby's","Sheldon","Sheldon's","Shelia","Shelia's","Shelley","Shelley's","Shelly","Shelly's","Shelton",
    					  "Shelton's","Shenandoah","Shenandoah's","Shenyang","Shenyang's","Sheol","Sheol's","Shepard","Shepard's",
    					  "Shepherd","Shepherd's","Sheppard","Sheppard's","Sheratan","Sheratan's","Sheraton","Sheraton's","Sheree",
    					  "Sheree's","Sheri","Sheri's","Sheridan","Sheridan's","Sherlock","Sherlock's","Sherman","Sherman's","Sherpa",
    					  "Sherpa's","Sherpas","Sherri","Sherri's","Sherrie","Sherrie's","Sherry","Sherry's","Sherwood","Sherwood's",
    					  "Sheryl","Sheryl's","Shetland","Shetlands","Shevardnadze","Shevardnadze's","Shevat","Shevat's","Shi'ite",
    					  "Shields","Shields's","Shijiazhuang","Shikoku","Shikoku's","Shillong","Shillong's","Shiloh","Shiloh's",
    					  "Shinto","Shinto's","Shintoism","Shintoisms","Shintos","Shiraz","Shiraz's","Shirley","Shirley's","Shiva",
    					  "Shiva's","Shockley","Shockley's","Short","Short's","Shorthorn","Shorthorn's","Shoshone","Shoshone's",
    					  "Shostakovitch","Shostakovitch's","Shreveport","Shreveport's","Shriner","Shriner's","Shropshire",
    					  "Shropshire's","Shula","Shula's","Shylock","Shylock's","Shylockian","Shylockian's","Si","Si's","Siam",
    					  "Siam's","Siamese","Siamese's","Sian","Sian's","Sibelius","Sibelius's","Siberia","Siberia's","Siberian",
    					  "Sibyl","Sibyl's","Sicilian","Sicilians","Sicily","Sicily's","Sid","Sid's","Siddhartha","Siddhartha's",
    					  "Sidney","Sidney's","Siegfried","Siegfried's","Siemens","Siemens's","Sierpinski","Sierpinski's",
    					  "Sigismund","Sigismund's","Sigmund","Sigmund's","Sigurd","Sigurd's","Sihanouk","Sihanouk's","Sikh",
    					  "Sikh's","Sikhism","Sikhism's","Sikhisms","Sikhs","Sikkim","Sikkim's","Sikkimese","Sikorsky","Sikorsky's",
    					  "Silas","Silas's","Silurian","Silva","Silva's","Silvia","Silvia's","Simenon","Simenon's","Simmental",
    					  "Simmons","Simmons's","Simon","Simon's","Simone","Simone's","Simpson","Simpson's","Sims","Sinai","Sinai's",
    					  "Sinatra","Sinatra's","Sinclair","Sinclair's","Sindbad","Sindbad's","Sindhi","Sindhi's","Singapore",
    					  "Singapore's","Singer","Singer's","Singleton","Singleton's","Sinhalese","Sinhalese's","Sinkiang","Sinkiang's",
    					  "Sioux","Sioux's","Sirius","Sirius's","Sister","Sisters","Sistine","Sisyphean","Sisyphus","Sisyphus's",
    					  "Siva","Siva's","Sivan","Sivan's","Sjaelland","Sjaelland's","Skinner","Skinner's","Skippy","Skippy's","Skopje",
    					  "Skopje's","Skye","Skye's","Skylab","Skylab's","Slater","Slater's","Slav","Slav's","Slavic","Slavic's",
    					  "Slavonic","Slavonic's","Slavs","Slinky","Slinky's","Sloan","Sloan's","Sloane","Sloane's","Slocum",
    					  "Slocum's","Slovak","Slovakia","Slovakia's","Slovakian","Slovakians","Slovaks","Slovenia","Slovenia's",
    					  "Slovenian","Slovenians","Slurpee","Slurpee's","Sm","Sm's","Small","Small's","Smetana","Smetana's")
  
	val t =  dictionary.bktree
	println(  t -?- "Shields"  ) // true
    println(  t -?- "Shiels"  )  // false
    
    
}