# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "55.55.55.100"
  config.vm.synced_folder "shared", "/home/vagrant/shared/"

  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update     
     sudo apt-get install -y lxc
     sudo apt-get install -y wget
     sudo wget -qO- https://get.docker.com/ | sudo bash
     sudo apt-get install -y curl
     sudo apt-get install -y git    
     sudo curl -L https://github.com/docker/compose/releases/download/1.3.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
     sudo chmod +x /usr/local/bin/docker-compose
  SHELL

end
