Vagrant.configure(2) do |config|
  config.vm.define "telemetry" do |node|
    config.vm.box = "bento/centos-7.1"
    config.vm.network "private_network", ip: "10.10.10.255"
    config.vm.synced_folder ".", "/home/vagrant/shared/"
    config.vm.provision "shell", :path => "provision-base.sh"
    config.vm.provision "shell", :path => "provision-java-scala.sh"
    config.vm.provision "shell", :path => "provision-ansible.sh"
    config.vm.provision "shell", :path => "provision-kafka.sh"    
    config.vm.provision "shell", :path => "provision-cassandra.sh"
    config.vm.provision "shell", :path => "provision-jetty.sh"
    config.vm.provision "shell", :path => "provision-collectd.sh"
    config.vm.provision "shell", :path => "provision-elk.sh"
  end  
end