# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "55.55.55.101"
  config.vm.synced_folder ".", "/home/vagrant/shared/"

  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update     
     sudo apt-get install -y wget
     sudo apt-get install -y curl
     sudo apt-get install -y vim
     sudo apt-get install -y git    
     sudo apt-get install -y build-essential
     #
     # Installs RVM
     #
     sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
     sudo curl -sSL https://get.rvm.io | bash -s stable
     sudo su
     source /etc/profile.d/rvm.sh
     #
     # Install Ruby 2.1.x in RVM
     #
     rvm install 2.1
     rvm use 2.1
  SHELL

end
