# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "55.55.55.102"
  config.vm.synced_folder ".", "/home/vagrant/shared/"

  #config.vm.provision "file", source: "conf/sbt.sh", destination: "/home/vagrant/bin/sbt"
    
  config.vm.provision "shell", inline: <<-SHELL    
    #
    # Update and install basic linux programs for development
    #
    sudo apt-get update     
    sudo apt-get install -y wget
    sudo apt-get install -y curl
    sudo apt-get install -y vim
    sudo apt-get install -y git    
    sudo apt-get install -y build-essential
    sudo apt-get install -y unzip 
    #
    # Install Java 8 
    #
    cd /opt
    sudo wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.tar.gz"
    sudo tar -xzvf jdk-8u45-linux-x64.tar.gz
    sudo rm -rf jdk-8u45-linux-x64.tar.gz
    sudo echo "export JAVA_HOME=/opt/jdk1.8.0_45" >> /home/vagrant/.bashrc
    sudo echo "export JRE_HOME=/opt/jdk1.8.0_45/jre" >> /home/vagrant/.bashrc
    sudo echo "export PATH=\$PATH:/opt/jdk1.8.0_45/bin:/opt/jdk1.8.0_45/jre/bin" >> /home/vagrant/.bashrc
    #
    # Install Maven 3.3
    #
    sudo wget http://mirror.nbtelecom.com.br/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
    sudo tar -xzvf apache-maven-3.3.3-bin.tar.gz
    sudo rm -rf apache-maven-3.3.3-bin.tar.gz
    sudo echo "export M2_HOME=/opt/apache-maven-3.3.3" >> /home/vagrant/.bashrc
    sudo echo "export PATH=\$PATH:/opt/apache-maven-3.3.3/bin" >> /home/vagrant/.bashrc
    #
    # Install Groovy 2.4
    #
    sudo wget http://dl.bintray.com/groovy/maven/groovy-binary-2.4.3.zip
    sudo unzip groovy-binary-2.4.3.zip -d /opt/
    sudo rm -rf groovy-binary-2.4.3.zip
    sudo echo "export GROOVY_HOME=/opt/groovy-2.4.3" >> /home/vagrant/.bashrc
    sudo echo "export PATH=\$PATH:/opt/groovy-2.4.3/bin" >> /home/vagrant/.bashrc

    #
    # Install Gradle 2.4
    #
    sudo wget https://services.gradle.org/distributions/gradle-2.4-bin.zip
    sudo unzip gradle-2.4-bin.zip -d /opt/
    sudo rm -rf gradle-2.4-bin.zip 
    sudo echo "export GRADLE_HOME=/opt/gradle-2.4" >> /home/vagrant/.bashrc
    sudo echo "export PATH=\$PATH:/opt/gradle-2.4/bin" >> /home/vagrant/.bashrc
    #
    # Install Clojure 1.6
    #
    sudo wget http://repo1.maven.org/maven2/org/clojure/clojure/1.6.0/clojure-1.6.0.zip
    sudo unzip clojure-1.6.0.zip -d /opt/
    sudo rm -rf clojure-1.6.0.zip
    sudo cp /home/vagrant/shared/conf/clojure.sh /opt/clojure-1.6.0/clojure
    sudo chmod +x /opt/clojure-1.6.0/clojure
    sudo echo "export CLOJURE_HOME=/opt/clojure-1.6.0" >> /home/vagrant/.bashrc
    sudo echo "export PATH=\$PATH:/opt/clojure-1.6.0" >> /home/vagrant/.bashrc
    #
    # Install Lein
    #
    sudo mkdir /home/vagrant/bin
    cd /home/vagrant/bin/
    sudo wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    sudo chmod a+x /home/vagrant/bin/lein
    sudo echo "export PATH=\$PATH:/home/vagrant/bin" >> /home/vagrant/.bashrc
    #
    # Install Scala 2.11
    #
    sudo wget http://downloads.typesafe.com/scala/2.11.6/scala-2.11.6.tgz
    sudo tar -xzvf scala-2.11.6.tgz
    sudo rm -rf scala-2.11.6.tgz
    sudo echo "export SCALA_HOME=/opt/scala-2.11.6" >> /home/vagrant/.bashrc
    sudo echo "export PATH=\$PATH:/opt/scala-2.11.6/bin" >> /home/vagrant/.bashrc
    #
    # Install SBT 0.13
    #
    cd /home/vagrant/bin/
    sudo wget https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
    sudo cp /home/vagrant/shared/conf/sbt.sh /home/vagrant/bin/sbt
    sudo chmod u+x /home/vagrant/bin/sbt
    sudo chmod +x /home/vagrant/bin/sbt
    #
    # Source the new bashrc
    # We also need finish install lein, it will self install thats why we do lein for last
    #
    sudo echo "alias cls='clear'" >> /home/vagrant/.bashrc
    source /home/vagrant/.bashrc
  SHELL

end
