#!/bin/bash
# chkconfig: 2345 95 20
# description: This script does some stuff
# processname: java

start() {
   echo "Starting tomcat..."
   export JAVA_HOME=/home/ec2-user/jdk1.8.0_45
   export JRE_HOME=/home/ec2-user/jdk1.8.0_45/jre
   export PATH=$PATH:/home/ec2-user/jdk1.8.0_45/bin:/home/ec2-user/jdk1.8.0_45/jre/bin
   export CATALINA_HOME=/home/ec2-user/apache-tomcat-8.0.35/

  export ASG_NAME="asg_dynomite"
  export EC2_REGION="us-west-2"

   cd /home/ec2-user/apache-tomcat-8.0.35/ && /home/ec2-user/apache-tomcat-8.0.35/bin/catalina.sh start &
}

stop() {
   echo "stop"
   PID=`pgrep java`
   if [[ "" !=  "$PID" ]]; then
      echo "killing $PID"
      sudo kill -9 $PID
   fi
}

case "$1" in start)
  start
;;
  stop)
  stop
;;
*)

echo $"Usage: $0 {start|stop}"
RETVAL=1
esac
exit 0


