---
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 'm5.large'
      KeyName: 'pacheco_kp'   # keypair must already exist
      ImageId: 'ami-4de93c2d' # AMI need exist